# Generated by Django 2.2.6 on 2019-12-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_category_todos_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority_count',
            field=models.PositiveIntegerField(default=125),
        ),
    ]
