# Generated by Django 2.2.6 on 2019-12-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_todoitem_priority_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
